/********************************************************************
* plotDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error plotDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableplotDict();
extern void G__cpp_setup_inheritanceplotDict();
extern void G__cpp_setup_typetableplotDict();
extern void G__cpp_setup_memvarplotDict();
extern void G__cpp_setup_globalplotDict();
extern void G__cpp_setup_memfuncplotDict();
extern void G__cpp_setup_funcplotDict();
extern void G__set_cpp_environmentplotDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "PrettyAnitaEvent.h"
#include "CorrelationSummary.h"
#include "UsefulAdu5Pat.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__plotDictLN_TClass;
extern G__linked_taginfo G__plotDictLN_TBuffer;
extern G__linked_taginfo G__plotDictLN_TMemberInspector;
extern G__linked_taginfo G__plotDictLN_TObject;
extern G__linked_taginfo G__plotDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__plotDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__plotDictLN_TGraph;
extern G__linked_taginfo G__plotDictLN_WaveCalType;
extern G__linked_taginfo G__plotDictLN_WaveCalTypecLcLEWaveCalType;
extern G__linked_taginfo G__plotDictLN_AnitaPol;
extern G__linked_taginfo G__plotDictLN_AnitaPolcLcLEAnitaPol;
extern G__linked_taginfo G__plotDictLN_RawAnitaEvent;
extern G__linked_taginfo G__plotDictLN_PrettyAnitaHk;
extern G__linked_taginfo G__plotDictLN_UsefulAnitaEvent;
extern G__linked_taginfo G__plotDictLN_CorrelationSummary;
extern G__linked_taginfo G__plotDictLN_TCanvas;
extern G__linked_taginfo G__plotDictLN_PrettyAnitaEvent;
extern G__linked_taginfo G__plotDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__plotDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__plotDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__plotDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__plotDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__plotDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__plotDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__plotDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__plotDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__plotDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__plotDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__plotDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__plotDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__plotDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__plotDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__plotDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__plotDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__plotDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__plotDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__plotDictLN_TVector3;
extern G__linked_taginfo G__plotDictLN_Adu5Pat;
extern G__linked_taginfo G__plotDictLN_UsefulAdu5Pat;

/* STUB derived class for protected member access */
